### PR TITLE
add web in Profile and update readme for local deployment

### PR DESCRIPTION
**Pull request by jollychang**
add web in Profile and update readme for local deployment, 
https://github.com/fcelda/gitlab2jenkins/issues/5

### CODE REVIEW

**Comment by fcelda** [comment]
Thank you for the PR. The web is served by Passenger via Rack on OpenShift, so starting another web process by foreman is not entirely desired. But I guess the apps are namespaced and the port should not be exposed outside the OpenShift gear, right?

**Comment by jollychang** [comment]
I'm not quite sure for openshift :(
The Gitlab2jenkins is web ui is nice :)

**Comment by fcelda** [comment]
OK, I will try this on OpenShift and we will see, what happens. If it works, I will merge. Thanks anyway!

**Comment by fcelda** [comment]
Sorry, I had to revert the change. This breaks OpenShift deployment, because we cannot bind additional ports there.

**Pull request merged**
